name: rva_flutter_example
description: Minimal example for the rva_flutter plugin.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rva_flutter:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/hero.rva
